Fix and test Windows build in AppVeyor (#25)
* Update Windows DLL names (based on https://github.com/hdfeos/pyhdf/commit/3f74accdc91aca6f229720ab8a1a4dd7480404a6)

* Test Windows build in AppVeyor using Miniconda

* Fix Windows temporary file issue:
```
ERROR: pyhdf.test_SD.test_long_varname
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\pyhdf\pyhdf\SD.py", line 1410, in __init__
    os.remove(path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pyhdf_dr_yvjlo.hdf'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\projects\pyhdf\pyhdf\test_SD.py", line 17, in test_long_varname
    sd = pyhdf.SD.SD(path, SDC.WRITE|SDC.CREATE|SDC.TRUNC)
  File "C:\projects\pyhdf\pyhdf\SD.py", line 1412, in __init__
    raise HDF4Error(msg)
pyhdf.error.HDF4Error: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pyhdf_dr_yvjlo.hdf'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Miniconda3\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\projects\pyhdf\pyhdf\test_SD.py", line 31, in test_long_varname
    os.unlink(path)
PermissionError: [WinError 32] The process cannot access the file
because it is being used by another process:
'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pyhdf_dr_yvjlo.hdf'
```