Fix txttohdf example
Probably breaking due to changes in recent numpy releases.
Use builtin min function instead numpy.min function.

 Traceback (most recent call last):
  File "/home/runner/work/pyhdf/pyhdf/examples/txttohdf/txttohdf.py", line 69, in <module>
    txtToHDF('temp.txt', hdfFile, 'temperature',
  File "/home/runner/work/pyhdf/pyhdf/examples/txttohdf/txttohdf.py", line 43, in txtToHDF
    minVal = min(minVal, minE)
  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 2953, in min
    return _wrapreduction(a, np.minimum, 'min', axis, None, out,
  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return reduction(axis=axis, out=out, **passkwargs)
  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/numpy/core/_methods.py", line 45, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial, where)
TypeError: 'numpy.float64' object cannot be interpreted as an integer