Fix build failure due to import_array return value on older numpy
The import_array macro returns NULL instead of int on error, so we get
this compilation failure:
```
pyhdf/hdfext_wrap.c:11550:3: error: incompatible pointer to integer conversion returning 'void *' from a function with result type 'int' [-Wint-conversion]
 11550 |   import_array();
       |   ^~~~~~~~~~~~~~
```

Newer versions of numpy knows about this incompatibility with swig init
code and has a workaround. We can just use import_array1 and be
explicit about the return value. See:
See https://numpy.org/doc/stable/reference/c-api/array.html#c.import_array